"""Generate web/js/data/world-dots.js: the dot-matrix land mask behind the threat map.

Source data: Natural Earth 1:110m land (public domain), as TopoJSON from the
`world-atlas` npm package (ISC):  https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/land-110m.json

    python scripts/build_world_dots.py path/to/land-110m.json

The output is a tiny equirectangular grid (one hex string per row, 1 bit per cell), so the
browser needs no map library and no network access to draw the world.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

STEP = 2.0                       # degrees per dot
LON_MIN, LON_MAX = -180.0, 180.0
LAT_MIN, LAT_MAX = -58.0, 82.0   # crop Antarctica and the high Arctic
OUT = Path(__file__).resolve().parent.parent / "web" / "js" / "data" / "world-dots.js"


def decode_arcs(topology: dict) -> list[list[tuple[float, float]]]:
    """TopoJSON arcs are quantized and delta-encoded; undo both."""
    (sx, sy), (tx, ty) = topology["transform"]["scale"], topology["transform"]["translate"]
    arcs = []
    for arc in topology["arcs"]:
        x = y = 0
        points = []
        for dx, dy in arc:
            x, y = x + dx, y + dy
            points.append((x * sx + tx, y * sy + ty))
        arcs.append(points)
    return arcs


def ring(indices: list[int], arcs: list[list[tuple[float, float]]]) -> list[tuple[float, float]]:
    points: list[tuple[float, float]] = []
    for i in indices:
        arc = arcs[i] if i >= 0 else arcs[~i][::-1]  # negative index = arc i reversed
        points.extend(arc[1:] if points else arc)
    return points


def inside(lon: float, lat: float, rings: list[list[tuple[float, float]]]) -> bool:
    """Even-odd rule across all rings, so holes (lakes, seas) cut out correctly."""
    hit = False
    for pts in rings:
        for (x1, y1), (x2, y2) in zip(pts, pts[1:] + pts[:1], strict=True):
            if (y1 > lat) != (y2 > lat) and lon < (x2 - x1) * (lat - y1) / (y2 - y1) + x1:
                hit = not hit
    return hit


def main(source: str) -> None:
    topology = json.loads(Path(source).read_text(encoding="utf-8"))
    arcs = decode_arcs(topology)
    polygons = []
    for geometry in topology["objects"]["land"]["geometries"]:
        parts = geometry["arcs"] if geometry["type"] == "MultiPolygon" else [geometry["arcs"]]
        polygons += [[ring(r, arcs) for r in polygon] for polygon in parts]
    boxes = [(min(x for r in p for x, _ in r), max(x for r in p for x, _ in r),
              min(y for r in p for _, y in r), max(y for r in p for _, y in r)) for p in polygons]

    cols = int((LON_MAX - LON_MIN) / STEP)
    rows = int((LAT_MAX - LAT_MIN) / STEP)
    encoded, land = [], 0
    for r in range(rows):
        lat = LAT_MAX - (r + 0.5) * STEP
        bits = []
        for c in range(cols):
            lon = LON_MIN + (c + 0.5) * STEP
            on = any(x0 <= lon <= x1 and y0 <= lat <= y1 and inside(lon, lat, poly)
                     for poly, (x0, x1, y0, y1) in zip(polygons, boxes, strict=True))
            bits.append("1" if on else "0")
            land += on
        bitstring = "".join(bits).ljust((cols + 3) // 4 * 4, "0")
        encoded.append(f"{int(bitstring, 2):0{len(bitstring) // 4}x}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/build_world_dots.py from Natural Earth 1:110m land (public domain). Do not edit.\n"
        f"export const WORLD = {{ cols: {cols}, rows: {rows}, step: {STEP}, lonMin: {LON_MIN}, latMax: {LAT_MAX},\n"
        f"  latMin: {LAT_MIN}, mask: {json.dumps(encoded)} }};\n",
        encoding="utf-8", newline="\n",
    )
    print(f"{cols}x{rows} grid, {land} land dots -> {OUT}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "land-110m.json")
